"""
DeepAlpha Example Strategy for Freqtrade
=========================================

A minimal Freqtrade strategy demonstrating how to use the DeepAlpha
FreqAI model. This strategy:

- Defines technical indicator features for FreqAI
- Uses Triple Barrier labels generated by the DeepAlpha model
- Filters entries using meta-labeling confidence scores
- Implements basic risk management via stop-loss and ROI

Usage:
    freqtrade trade --strategy DeepAlphaStrategy --freqaimodel DeepAlphaModel

Author: DeepAlpha Team
License: MIT
"""

from __future__ import annotations

import logging
from functools import reduce

import numpy as np
import pandas as pd
import talib.abstract as ta
from pandas import DataFrame

from freqtrade.strategy import IStrategy, merge_informative_pair
from freqtrade.strategy.parameters import IntParameter, DecimalParameter

logger = logging.getLogger(__name__)


class DeepAlphaStrategy(IStrategy):
    """
    Freqtrade strategy powered by DeepAlpha's ML pipeline.

    The strategy delegates all signal generation to the FreqAI model.
    Features are defined in `feature_engineering_*` methods and passed
    to the DeepAlpha model, which returns predictions and a confidence
    mask from meta-labeling.
    """

    # ---------------------------------------------------------------
    # Strategy configuration
    # ---------------------------------------------------------------

    INTERFACE_VERSION = 3

    # Minimal ROI table — the ML model handles exits primarily
    minimal_roi = {
        "0": 0.05,
        "30": 0.03,
        "60": 0.02,
        "120": 0.01,
    }

    stoploss = -0.03
    trailing_stop = True
    trailing_stop_positive = 0.01
    trailing_stop_positive_offset = 0.02

    timeframe = "5m"

    # FreqAI configuration
    freqai_info = {
        "enabled": True,
    }

    # Strategy parameters (optimizable)
    buy_prediction_threshold = DecimalParameter(
        0.5, 0.8, default=0.55, decimals=2, space="buy",
        optimize=True, load=True,
    )
    sell_prediction_threshold = DecimalParameter(
        0.5, 0.8, default=0.55, decimals=2, space="sell",
        optimize=True, load=True,
    )
    meta_confidence_threshold = DecimalParameter(
        0.5, 0.8, default=0.55, decimals=2, space="buy",
        optimize=True, load=True,
    )

    # ---------------------------------------------------------------
    # Feature engineering
    # ---------------------------------------------------------------

    def feature_engineering_expand_all(
        self, dataframe: DataFrame, period: int, metadata: dict, **kwargs
    ) -> DataFrame:
        """
        Create features that will be expanded across multiple periods.

        FreqAI automatically generates these features for each period
        defined in the config (e.g., 10, 20, 50 candles).
        """
        # Momentum indicators
        dataframe[f"%-rsi-period_{period}"] = ta.RSI(dataframe, timeperiod=period)
        dataframe[f"%-mfi-period_{period}"] = ta.MFI(dataframe, timeperiod=period)
        dataframe[f"%-adx-period_{period}"] = ta.ADX(dataframe, timeperiod=period)
        dataframe[f"%-cci-period_{period}"] = ta.CCI(dataframe, timeperiod=period)

        # Volatility
        bollinger = ta.BBANDS(dataframe, timeperiod=period, nbdevup=2, nbdevdn=2)
        dataframe[f"%-bb-width-period_{period}"] = (
            (bollinger["upperband"] - bollinger["lowerband"]) / bollinger["middleband"]
        )
        dataframe[f"%-bb-pct-period_{period}"] = (
            (dataframe["close"] - bollinger["lowerband"])
            / (bollinger["upperband"] - bollinger["lowerband"] + 1e-10)
        )
        dataframe[f"%-atr-period_{period}"] = ta.ATR(dataframe, timeperiod=period)

        # Trend
        dataframe[f"%-sma-period_{period}"] = ta.SMA(dataframe, timeperiod=period)
        dataframe[f"%-ema-period_{period}"] = ta.EMA(dataframe, timeperiod=period)
        dataframe[f"%-close-sma-ratio_{period}"] = (
            dataframe["close"] / (dataframe[f"%-sma-period_{period}"] + 1e-10)
        )

        # Volume
        dataframe[f"%-volume-sma-ratio_{period}"] = (
            dataframe["volume"]
            / (dataframe["volume"].rolling(period).mean() + 1e-10)
        )

        return dataframe

    def feature_engineering_expand_basic(
        self, dataframe: DataFrame, metadata: dict, **kwargs
    ) -> DataFrame:
        """
        Create features that are not expanded across multiple periods.
        """
        # MACD
        macd = ta.MACD(dataframe, fastperiod=12, slowperiod=26, signalperiod=9)
        dataframe["%-macd"] = macd["macd"]
        dataframe["%-macd-signal"] = macd["macdsignal"]
        dataframe["%-macd-hist"] = macd["macdhist"]

        # Stochastic
        stoch = ta.STOCH(dataframe, fastk_period=14, slowk_period=3, slowd_period=3)
        dataframe["%-slowk"] = stoch["slowk"]
        dataframe["%-slowd"] = stoch["slowd"]

        # Ichimoku
        dataframe["%-tenkan"] = (
            dataframe["high"].rolling(9).max() + dataframe["low"].rolling(9).min()
        ) / 2
        dataframe["%-kijun"] = (
            dataframe["high"].rolling(26).max() + dataframe["low"].rolling(26).min()
        ) / 2

        # Price-based features
        dataframe["%-pct-change"] = dataframe["close"].pct_change()
        dataframe["%-log-return"] = np.log(
            dataframe["close"] / dataframe["close"].shift(1)
        )

        # Candle patterns
        dataframe["%-body-ratio"] = (
            abs(dataframe["close"] - dataframe["open"])
            / (dataframe["high"] - dataframe["low"] + 1e-10)
        )
        dataframe["%-upper-shadow"] = (
            dataframe["high"]
            - dataframe[["close", "open"]].max(axis=1)
        ) / (dataframe["high"] - dataframe["low"] + 1e-10)

        return dataframe

    def feature_engineering_standard(
        self, dataframe: DataFrame, metadata: dict, **kwargs
    ) -> DataFrame:
        """
        Features computed after all expansion.  Also defines the target
        label column that the model will train on.
        """
        # Day-of-week and hour features
        dataframe["%-day-of-week"] = dataframe["date"].dt.dayofweek
        dataframe["%-hour"] = dataframe["date"].dt.hour

        # Target label: the DeepAlpha model generates Triple Barrier labels
        # internally, but we provide a default directional label here as
        # a fallback.
        dataframe["&-label"] = (
            dataframe["close"].shift(-1) > dataframe["close"]
        ).astype(int)

        return dataframe

    def set_freqai_targets(self, dataframe: DataFrame, metadata: dict, **kwargs) -> DataFrame:
        """
        Define the target variable for FreqAI training.

        The DeepAlpha model overrides this with Triple Barrier labels
        when configured, but we provide a simple directional target
        as the default.
        """
        dataframe["&-target"] = (
            dataframe["close"].shift(-1) > dataframe["close"]
        ).astype(int)

        return dataframe

    # ---------------------------------------------------------------
    # Signal generation
    # ---------------------------------------------------------------

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        FreqAI handles indicator generation via feature_engineering methods.
        This method is intentionally minimal.
        """
        # FreqAI populates predictions automatically
        dataframe = self.freqai.start(dataframe, metadata, self)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Generate entry signals from DeepAlpha model predictions.

        A long entry requires:
        1. Model predicts class 1 (bullish)
        2. Meta-labeling confidence above threshold (if available)
        3. Model is not in do_not_act state
        """
        conditions_long = []

        # Primary prediction: bullish
        if "prediction" in dataframe.columns:
            conditions_long.append(dataframe["prediction"] == 1)

        # Meta-labeling confidence filter
        if "meta_confidence" in dataframe.columns:
            conditions_long.append(
                dataframe["meta_confidence"] >= self.meta_confidence_threshold.value
            )

        # Do-not-act filter
        if "do_not_act" in dataframe.columns:
            conditions_long.append(dataframe["do_not_act"] == 0)

        if conditions_long:
            dataframe.loc[
                reduce(lambda a, b: a & b, conditions_long),
                "enter_long",
            ] = 1

        # Short entries (if enabled)
        conditions_short = []
        if "prediction" in dataframe.columns:
            conditions_short.append(dataframe["prediction"] == -1)
        if "meta_confidence" in dataframe.columns:
            conditions_short.append(
                dataframe["meta_confidence"] >= self.meta_confidence_threshold.value
            )
        if "do_not_act" in dataframe.columns:
            conditions_short.append(dataframe["do_not_act"] == 0)

        if conditions_short:
            dataframe.loc[
                reduce(lambda a, b: a & b, conditions_short),
                "enter_short",
            ] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Generate exit signals. The strategy primarily relies on
        ROI / stoploss / trailing stop for exits, with model-based
        exits as an additional layer.
        """
        # Exit long when model predicts bearish
        if "prediction" in dataframe.columns:
            dataframe.loc[
                dataframe["prediction"] == -1,
                "exit_long",
            ] = 1
            dataframe.loc[
                dataframe["prediction"] == 1,
                "exit_short",
            ] = 1

        return dataframe
